### ISSUE TITLE
Regex values in ignore don't seem to work

### ISSUE THREAD

**Issue by MathewKostiuk** [halfhelix/Kit#28]
Hi there,

I'm working with the Tomorrow Agency where we're using Kit. I'm looking to prevent the `templates/*.json` files from being deployed but I'm not having success with the Regex pattern. Here's my `kit.config.js`:

```js
module.exports = {
  ignore: [
    /templates\/.*[.]json/
  ],
}
```

However, I still see the JSON templates being uploaded when running `kit deploy`. This is with the `ignore` key in the top-level after `module.exports`. I've also tried with `ignore` nested within the individual environments and I see the same results there.

Other files are ignored if I add in the full path.

Kit version: 1.1.1

Is this a known issue? I'm happy to provide any other information that may help debugging, just let me know!

Thank you

**Comment by maxrolon** [comment]
Hey @MathewKostiuk We've just deployed 1.1.2 which should include this functionality. Can you try this again and let me know if the issue persists?

**Comment by MathewKostiuk** [comment]
@maxrolon Thanks for the response! I've just tried this again with the updated version and it's working just as expected. `kit.config.js` is looking much better now!

**Comment by maxrolon** [comment]
@MathewKostiuk Awesome! In the future I can get back to you faster, sorry for the delay with this one.
