### ISSUE TITLE
Not an issue, but a question. Which of the various packages are responsible for handling browsersync?

### ISSUE THREAD

**Issue by adrianocr** [halfhelix/Kit#5]
I'm working on a project where the theme already exists and I'm doing some overhauling of the sections and JS but can't fully replace the theme with something like Kit or Slate. 

I got my webpack config to work but I'm having a hard time making browsersync work so I was hoping to "borrow" the method you guys are using to make it proxy and reload correctly based on themekit uploading files.

**Comment by maxrolon** [comment]
Hey @adrianocr I am sorry that we didn't get around to answering your question. I assuming by how old this question is and the fact that it is now closed this is no longer relevant but let me know if there is anything we can help with.
